### ISSUE TITLE
pluginName(eggProxy) is different from pluginConfigName(proxy)

### ISSUE THREAD

**Issue by xcodebuild** [xxeric/egg-proxy#1]
`WARN 61486 [egg:loader] pluginName(eggProxy) is different from pluginConfigName(proxy)`

```js
exports.eggProxy = {
};
```

not works however 

```js
exports.proxy = {
};
```

dose.

**Comment by xyeric** [comment]
Sorry, my carelessness. just updated the source code, but forgot the docs.

It has fixed in version 1.0.6.

config key has changed to `proxy`;

```
// config/plugin.js

exports.proxy = {
  enable: true,
  package: 'egg-proxy'
};
```

```
// config/config.default.js

exports.proxy = {
  host: 'http://localhost:9000',
  match: /^\/assets/
};
```
