### ISSUE TITLE
suppressRequestHeaders,suppressResponseHeaders

### ISSUE THREAD

**Issue by nickasam** [xxeric/egg-proxy#4]
您好，请问您一下，这两个是什么东西？？？不是很明白？？？？@xyeric

**Comment by xyeric** [comment]
@zheng199512 请问是哪里看到的？没有上下文我不太好判断哈哈

**Comment by nickasam** [comment]
https://github.com/popomore/koa-proxy  哇，您好，大神，我是在koa-proxy中看到的，查了一些没有发现这是个什么用途，谢谢，哇，大神merge了我的readme，开心～ @xyeric

**Comment by xyeric** [comment]
客气啦，看了下源码，这两个配置是用来阻止请求和返回的header的，可以查看下面的代码：
https://github.com/popomore/koa-proxy/blob/master/index.js#L65
https://github.com/popomore/koa-proxy/blob/master/index.js#L84

**Comment by nickasam** [comment]
哥哥哥哥哥哥，我想把你这个改成TS的模式，但是在`lib/context.js`中我改不了了，我不会改，导出的貌似是一个方法，在`extend/application.js`中以类的形式使用？？？不是很明白，求解答 @xyeric

**Comment by xyeric** [comment]
这个插件比较简单哈，extend/application.js这个文件应该是直接从egg的脚手架里面带出来的，刚看了下实现，貌似这个文件也是没必要

**Comment by nickasam** [comment]
好的，谢谢，哥哥，我打算改改代码，提交个PR，额...，年后您可以看一下~Thank you，嘻嘻

**Comment by xyeric** [comment]
客气啦，新年快乐~
