### ISSUE TITLE
如何在使用proxy时，在发生请求时触发middleware里面的方法

### ISSUE THREAD

**Issue by shengpinghu** [xxeric/egg-proxy#6]
现在在使用proxy插件时，在发生请求时无法触发middleware里面的access方法,通过proxy代理的请求是没有日志信息的

**Comment by xyeric** [comment]
@shengpinghu 能详细描述下吗？方便提供示例代码的话最好了

**Comment by qq735675958** [comment]
按照示例配好了，比如 我代理 这个 接口 https://www.tianqiapi.com/api   postman   config.proxy = {
    host: 'https://www.tianqiapi.com/',  
    match: /\/test/ // path pattern.
  };
postman 里面请求 http://localhost:3000/test/api/

没有任何反应  作者能否写个完整请求示例？

**Comment by xyeric** [comment]
@qq735675958 看一下最新的test~：https://github.com/xyeric/egg-proxy/blob/master/test/egg-proxy.test.js
